import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().int().positive().default(4000),
  FRONTEND_URL: z.url().default("http://localhost:3000"),
  DATABASE_URL: z.string().min(1),
  DIRECT_DATABASE_URL: z.string().min(1).optional(),
  JWT_ACCESS_SECRET: z.string().min(32),
  JWT_REFRESH_SECRET: z.string().min(32),
  API_URL: z.url().optional(),
  REDIS_URL: z.string().min(1).optional(),
  AWS_ACCESS_KEY_ID: z.string().min(1).optional(),
  AWS_SECRET_ACCESS_KEY: z.string().min(1).optional(),
  AWS_REGION: z.string().min(1).optional(),
  AWS_S3_BUCKET: z.string().min(1).optional(),
  SENDGRID_API_KEY: z.string().min(1).optional(),
  SENDGRID_FROM_EMAIL: z.email().optional(),
  SENDGRID_FROM_NAME: z.string().min(1).optional(),
  TERMII_API_KEY: z.string().min(1).optional(),
  TERMII_SENDER_ID: z.string().min(1).optional(),
  PAYSTACK_SECRET_KEY: z.string().min(1).optional(),
  PAYSTACK_PUBLIC_KEY: z.string().min(1).optional(),
  FLUTTERWAVE_SECRET_KEY: z.string().min(1).optional(),
  FLUTTERWAVE_PUBLIC_KEY: z.string().min(1).optional(),
  FLUTTERWAVE_ENCRYPTION_KEY: z.string().min(1).optional(),
  VIRTUAL_ACCOUNT_PROVIDER: z.enum(["providus", "wema"]).optional(),
  PROVIDUS_CLIENT_ID: z.string().min(1).optional(),
  PROVIDUS_SECRET_KEY: z.string().min(1).optional(),
  WEMA_CLIENT_ID: z.string().min(1).optional(),
  WEMA_SECRET_KEY: z.string().min(1).optional(),
  KYC_PROVIDER: z.enum(["youverify", "smile", "prembly"]).optional(),
  YOUVERIFY_API_KEY: z.string().min(1).optional(),
  SMILE_PARTNER_ID: z.string().min(1).optional(),
  SMILE_API_KEY: z.string().min(1).optional(),
  PREMBLY_APP_ID: z.string().min(1).optional(),
  PREMBLY_X_API_KEY: z.string().min(1).optional(),
  TASK_MARKETPLACE_BASE_URL: z.url().optional(),
  TASK_MARKETPLACE_WEBHOOK_SECRET: z.string().min(1).optional(),
  TASK_MARKETPLACE_CLIENT_ID: z.string().min(1).optional(),
  TASK_MARKETPLACE_CLIENT_SECRET: z.string().min(1).optional(),
  FIELD_ENCRYPTION_KEY: z.string().min(1).optional(),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().optional(),
  RATE_LIMIT_MAX_REQUESTS: z.coerce.number().int().positive().optional(),
  AUTH_RATE_LIMIT_MAX: z.coerce.number().int().positive().optional()
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  FRONTEND_URL: process.env.FRONTEND_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  DIRECT_DATABASE_URL: process.env.DIRECT_DATABASE_URL,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  API_URL: process.env.API_URL,
  REDIS_URL: process.env.REDIS_URL,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_REGION: process.env.AWS_REGION,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_FROM_EMAIL: process.env.SENDGRID_FROM_EMAIL,
  SENDGRID_FROM_NAME: process.env.SENDGRID_FROM_NAME,
  TERMII_API_KEY: process.env.TERMII_API_KEY,
  TERMII_SENDER_ID: process.env.TERMII_SENDER_ID,
  PAYSTACK_SECRET_KEY: process.env.PAYSTACK_SECRET_KEY,
  PAYSTACK_PUBLIC_KEY: process.env.PAYSTACK_PUBLIC_KEY,
  FLUTTERWAVE_SECRET_KEY: process.env.FLUTTERWAVE_SECRET_KEY,
  FLUTTERWAVE_PUBLIC_KEY: process.env.FLUTTERWAVE_PUBLIC_KEY,
  FLUTTERWAVE_ENCRYPTION_KEY: process.env.FLUTTERWAVE_ENCRYPTION_KEY,
  VIRTUAL_ACCOUNT_PROVIDER: process.env.VIRTUAL_ACCOUNT_PROVIDER,
  PROVIDUS_CLIENT_ID: process.env.PROVIDUS_CLIENT_ID,
  PROVIDUS_SECRET_KEY: process.env.PROVIDUS_SECRET_KEY,
  WEMA_CLIENT_ID: process.env.WEMA_CLIENT_ID,
  WEMA_SECRET_KEY: process.env.WEMA_SECRET_KEY,
  KYC_PROVIDER: process.env.KYC_PROVIDER,
  YOUVERIFY_API_KEY: process.env.YOUVERIFY_API_KEY,
  SMILE_PARTNER_ID: process.env.SMILE_PARTNER_ID,
  SMILE_API_KEY: process.env.SMILE_API_KEY,
  PREMBLY_APP_ID: process.env.PREMBLY_APP_ID,
  PREMBLY_X_API_KEY: process.env.PREMBLY_X_API_KEY,
  TASK_MARKETPLACE_BASE_URL: process.env.TASK_MARKETPLACE_BASE_URL,
  TASK_MARKETPLACE_WEBHOOK_SECRET: process.env.TASK_MARKETPLACE_WEBHOOK_SECRET,
  TASK_MARKETPLACE_CLIENT_ID: process.env.TASK_MARKETPLACE_CLIENT_ID,
  TASK_MARKETPLACE_CLIENT_SECRET: process.env.TASK_MARKETPLACE_CLIENT_SECRET,
  FIELD_ENCRYPTION_KEY: process.env.FIELD_ENCRYPTION_KEY,
  RATE_LIMIT_WINDOW_MS: process.env.RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX_REQUESTS: process.env.RATE_LIMIT_MAX_REQUESTS,
  AUTH_RATE_LIMIT_MAX: process.env.AUTH_RATE_LIMIT_MAX
});
